#!/usr/bin/env python3
"""Assemble the public site from src/.

Why this exists: the page is written as one file per section (src/page/) and
one stylesheet per concern (src/css/) so every source file stays small and
easy to edit. The browser still gets a single index.html and a single
style.css. Run it after any edit under src/:

    ./build.py

No dependencies beyond Python 3. It also warns about any hand-written file
over 200 lines, which is the house rule for this repo.
"""
from pathlib import Path
import hashlib
import sys
import time

ROOT = Path(__file__).resolve().parent
SRC = ROOT / 'src'
SITE = ROOT / 'site'
LINE_LIMIT = 200
HTML_BANNER = '<!-- GENERATED by build.py from src/page/*.html. Edit those files, not this one. -->\n'
CSS_BANNER = '/* GENERATED by build.py from src/css/*.css. Edit those files, not this one. */\n'


def concat(folder: str, suffix: str) -> tuple[list[Path], str]:
    parts = sorted((SRC / folder).glob(f'*{suffix}'))
    return parts, ''.join(p.read_text(encoding='utf-8') for p in parts)


def short_hash(text: str) -> str:
    return hashlib.sha256(text.encode('utf-8')).hexdigest()[:8]


def lint_line_counts() -> int:
    """Report hand-written files over the limit. Generated files are exempt."""
    over = 0
    for folder in (SRC, SITE / 'js', ROOT / 'api'):
        for path in sorted(folder.rglob('*')):
            if not path.is_file() or path.suffix not in {'.html', '.css', '.js', '.py', '.md'}:
                continue
            count = sum(1 for _ in path.open(encoding='utf-8'))
            if count > LINE_LIMIT:
                print(f'  WARNING {path.relative_to(ROOT)} is {count} lines (limit {LINE_LIMIT})')
                over += 1
    return over


def main() -> int:
    pages, html = concat('page', '.html')
    css_parts, css = concat('css', '.css')
    if not pages or not css_parts:
        print('refusing to build: src/page or src/css is empty, which would blank the live site')
        return 1
    js_text = ''.join(p.read_text(encoding='utf-8') for p in sorted((SITE / 'js').glob('*.js')))
    version = short_hash(css + js_text)
    html = html.replace('{{BUILD_DATE}}', time.strftime('%Y-%m-%d')).replace('{{V}}', version)
    first, _, rest = html.partition('\n')
    if first.lower().startswith('<!doctype'):
        html = first + '\n' + HTML_BANNER + rest  # keep the doctype as the very first line
    else:
        html = HTML_BANNER + html
    (SITE / 'index.html').write_text(html, encoding='utf-8')
    (SITE / 'style.css').write_text(CSS_BANNER + css, encoding='utf-8')
    print(f'site/index.html <- {len(pages)} partials, site/style.css <- {len(css_parts)} files (v={version})')
    over = lint_line_counts()
    return 1 if over and '--strict' in sys.argv else 0


if __name__ == '__main__':
    sys.exit(main())
